### ISSUE TITLE
Error Requested resource does not exist dialog box pops up

### ISSUE THREAD

**Issue by shahtab** [elkozmon/zoonavigator#11]
Zookeeper ensemble is working correctly using confluent OSS 4.0.0-2.11  when checked manually 

Used docker-compose but after login this error pops up.

**Comment by elkozmon** [comment]
Hi, I'm sorry to hear that. 
Could you provide logs from both Docker containers at the time this error occurs please? I haven't seen this one before so logs would help greatly. Thanks :)

**Comment by shahtab** [comment]
upon docker-compose up  i get this

Creating zoonavigator-api ... done
Creating zoonavigator-web ... done
Creating zoonavigator-web ...
Attaching to zoonavigator-api, zoonavigator-web
zoonavigator-api | [warn] application - env var CRYPTO_SECRET: play.crypto.secret is deprecated, use play.http.secret.key instead
zoonavigator-api | [info] play.api.Play - Application started (Prod)
zoonavigator-api | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET / HTTP/1.1" 200 974 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /Roboto-Regular.b2a6341ae7440130ec4b.woff2 HTTP/1.1" 200 64184 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /config.json HTTP/1.1" 200 173 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:42 +0000] "GET /favicon-16x16.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-api | [warn] application - env var CRYPTO_SECRET: play.crypto.secret is deprecated, use play.http.secret.key instead
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /api/znode?path=/ HTTP/1.1" 404 78 "http://ulvelkp20:8000/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /Roboto-Medium.2741a14e49524efa6059.woff2 HTTP/1.1" 200 64808 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /fontawesome-webfont.af7ae505a9eed503f8b8.woff2 HTTP/1.1" 200 77160 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /MaterialIcons-Regular.570eb83859dc23dd0eec.woff2 HTTP/1.1" 200 44300 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/editor/data" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:14:43 +0000] "GET /favicon-16x16.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/editor/data" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:07 +0000] "DELETE /api/zsession HTTP/1.1" 200 46 "http://ulvelkp20:8000/editor/data" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:07 +0000] "GET /Roboto-Bold.ab96cca26751239828b8.woff2 HTTP/1.1" 200 63596 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:07 +0000] "GET /Roboto-RegularItalic.df8e3a9b9aed94341797.woff2 HTTP/1.1" 200 69276 "http://ulvelkp20:8000/styles.cfba770f8bec3c21b575.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:07 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:07 +0000] "GET /favicon-16x16.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:25 +0000] "POST /api/zsession HTTP/1.1" 200 191 "http://ulvelkp20:8000/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:25 +0000] "GET /api/znode?path=/ HTTP/1.1" 404 78 "http://ulvelkp20:8000/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:25 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/editor/data" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-web | 10.9.97.143 - - [08/Mar/2018:22:15:25 +0000] "GET /favicon-16x16.png HTTP/1.1" 200 974 "http://ulvelkp20:8000/editor/data" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
zoonavigator-api | [debug] application - Closing connection to ulvelkp31:2181,ulvelkp32:2181,ulvelkp33:2181,. Cause: EXPIRED

**Comment by elkozmon** [comment]
Thank you.

The log shows it fails on API call to endpoint that [was added](https://github.com/elkozmon/zoonavigator-api/commit/124d5fe053cb96135715ad0df1336e5ec41cc8da#diff-bc4f2a2b548c8d0fd6b61044503c1938R3) in version 0.3.0, so my guess is that you are running latest `zoonavigator-web` along with an old version of `zoonavigator-api`.

In your `docker-compose.yml` file try replacing `latest` docker tags with `0.3.0` for both images and try again please.

**Comment by shahtab** [comment]
That was it. Once I changed the image tag 0.3.0 to be pulled for both web and api all worked as expected.

I really love this interface.  Great work for the community from you.  Thanks

**Comment by elkozmon** [comment]
Glad I could help :) 

Thanks for the kind words, I appreciate it!
