### ISSUE TITLE
Connection to remove Zookeeper?

### ISSUE THREAD

**Issue by shrinandj** [elkozmon/zoonavigator#12]
Can you provide some details about how to connect with a Zookeeper instance running on a different machine? Typically this should take a Zookeeper hostname or IP and zookeeper port (2181?) as arguments. But I couldn't find any way of specifying that.

I'm trying to run this on Kubernetes. I can contribute some documentation about how I was able to do it if the above is possible.

**Comment by elkozmon** [comment]
Hi!

Yes, you take the ZooKeepers [connection string](https://stackoverflow.com/questions/30134447/what-does-an-apache-curator-connection-string-look-like) (comma-separated host:port instances) and enter that in the [connect forms](https://raw.githubusercontent.com/elkozmon/zoonavigator/2bbb4e130639e5297630edcb581f73ae4be44da0/images/connect-form.png) input labeled as _Connection string_ and click _Connect_.

There is a requirement though: ZooKeeper has to be accessible from **ZooNavigator API** instance using that connection string you provide. So the connection string depends on your networking between the ZooNavigator API and ZooKeeper servers.
