### ISSUE TITLE
Cannot login to the GUI

### ISSUE THREAD

**Issue by raarts** [elkozmon/zoonavigator#20]
What do I fill in for Auth username and Auth password? Thanks.

**Comment by elkozmon** [comment]
What kind of error are you getting? 

Username and password are optional, so feel free to leave those empty. Every username & password pair entered (you can enter many) serves as an extra ACL identity, so ZNodes could be given some permissions only for users logged in with certain credentials. [That's how ZooKeepers Auth scheme works](https://ihong5.wordpress.com/2014/07/24/apache-zookeeper-setting-acl-in-zookeeper-client/).
