### ISSUE TITLE
Docker state stuck in "health: starting"

### ISSUE THREAD

**Issue by monkybrain** [elkozmon/zoonavigator#25]
Hey! I recently added Zoonavigator to a Docker Compose project and I can access the web ui without any problems. However, I've noticed that the containers never seem to get past the "starting" stage. If I run  `docker-compose ps` I get the following output:

```
             Name                           Command                       State                                      Ports
------------------------------------------------------------------------------------------------------------------------------------------------------
zookeeper                        /docker-entrypoint.sh zkSe ...   Up                      0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp
zoonavigator-api                 ./run.sh                         Up (health: starting)   9000/tcp
zoonavigator-web                 ./run.sh                         Up (health: starting)   80/tcp, 0.0.0.0:32771->8000/tcp
```

This wasn't a problem until I started using [Traefik](https://traefik.io/), which doesn't register services until the starting stage has completed. Is there anything I can do here? Or is this a bug?

Btw, great project!

**Comment by monkybrain** [comment]
Sorry, I jumped the gun there. Apparently the container is registered as up & healthy after the first health check. The problem is that the first health check isn't triggered until 5 min after the container has started. Would it be possible to decrease the interval to say 30s? Or make the interval an option?

**Comment by elkozmon** [comment]
No problem, I just published the new Web build so feel free to use 'latest' images until version 0.6.0 is out :)

**Comment by monkybrain** [comment]
Great, thanks! I really appreciate the swift response.

**Comment by elkozmon** [comment]
Happy to help!

**Comment by elkozmon** [comment]
Hey! Unfortunately, I'm not gonna be able to finish all the things I meant for version '0.6.0' before December so I decided to roll out this fix a little sooner in a patch release with version '0.5.1'. 
Cheers!

**Comment by SoorajSundar1505** [comment]
Hey there, I have been facing the same issue when i am trying to run my selenium script in docker.
It got stuck after health check
Can anyone please help out?

![image](https://github.com/elkozmon/zoonavigator/assets/130204034/258d3ccd-adca-483e-ae74-563870497113)
