### ISSUE TITLE
Support reading GZipped data

### ISSUE THREAD

**Issue by jhalterman** [elkozmon/zoonavigator#26]
Similar to #24 :) It would be great if Zoonavigator supported reading and writing GZipped data. This should be fairly easy to do since it already supports JSON. Ex (in Scala, but you get the idea, using Jackson to deserialize Gzipped data):

```scala
def readGzippedOrCreateObjectNode(data: Array[Byte]): ObjectNode = {
  // See https://tools.ietf.org/html/rfc1952
  val isGzip: Boolean = data != null && data.length > 3 && data(0) == 31 && data(1) == -117 && data(2) == 8

  if (data == null) {
    mapper.createObjectNode()
  } else if (isGzip) {
    Try(mapper.readValue(new GZIPInputStream(new ByteArrayInputStream(data)), classOf[ObjectNode])).getOrElse(mapper.createObjectNode())
  } else {
    readOrCreateObjectNode(data)
  }
}

def compress(data: Array[Byte]): Array[Byte] = {
  val bytes: ByteArrayOutputStream = new ByteArrayOutputStream
  val out: GZIPOutputStream = new GZIPOutputStream(bytes)

  try {
    out.write(data)
  } finally {
    out.close()
  }

  bytes.toByteArray
}
```

**Comment by elkozmon** [comment]
Hey :) I just released version 0.6.0. There is a new select button in data editor where you can pick compression method (only gzip for now) and read/write compressed data. If you open up a node with already compressed data the editor should detect this and switch to the appropriate compression automatically.
