### ISSUE TITLE
Docker image for zoonavigator-web 0.6.0 results in Permission Denied

### ISSUE THREAD

**Issue by rajha-korithrien** [elkozmon/zoonavigator#35]
I have a Kubernetes based deployment of the prebuilt docker image
`elkozmon/zoonavigator-web:0.6.0`

When I deploy this image I get the following in the Pod logs:
```
2019/04/08 20:26:29 [emerg] 14#14: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```
The container then exits with a non-zero exit status and Kubernetes redeploys it. We end up in an infinite loop :-)

Have I missed some instructions about needing to create some kind of volume mount?

**Comment by elkozmon** [comment]
I'm sorry to hear that. You haven't missed anything I assure you. :)

I took a brief look at it and it seems that the issue here might be that the parent Docker image (nginx) requires to be run as root/privileged. I definitely intend to fix this if that's the case but until then I don't think I can help besides suggesting to lift the privileges, sorry.

**Comment by elkozmon** [comment]
I'll just drop this link here in case it proves useful later on.
http://pjdietz.com/2016/08/28/nginx-in-docker-without-root.html

**Comment by rajha-korithrien** [comment]
I see,
I am in a position to help fix this if you would like.
If you would like me to help, what branch would you like me to start with?
Thanks!

**Comment by elkozmon** [comment]
Absolutely, I'd appreciate the help 👍 

If it works with the alpine-based image from _nginxinc_, you can submit PR based on the master branch.

Thanks!

**Comment by rajha-korithrien** [comment]
A PR has been submitted:
https://github.com/elkozmon/zoonavigator-web/pull/9

Sorry to took so long.

**Comment by elkozmon** [comment]
Well done, thank you! I've merged it and published new version _0.6.1_.
