### ISSUE TITLE
Single distribution?

### ISSUE THREAD

**Issue by aadrian** [elkozmon/zoonavigator#37]
Hi,

Any chance considering a "single distribution"? I.e. to have a single JAR containing the JS resouces too? since the application is an SPA? (SBT could copy the JS resouces at build/package time).

It would greatly simplify the deployment for users (and also the required documentation).

Thank you.

**Comment by elkozmon** [comment]
Hi! 

Sure. To be honest, this has been on my mind for quite some time now. Next few weeks are going to be quite busy for me but eventually, I'd love to take this on.

Thank you for bringing this up :)

**Comment by elkozmon** [comment]
I'm happy to say that this is now done, see [new Docker repository](https://hub.docker.com/r/elkozmon/zoonavigator) and also updated [documentation](https://www.elkozmon.com/zoonavigator).

**Comment by aadrian** [comment]
@elkozmon Great! Thank you!
