### ISSUE TITLE
docker-compose start failed

### ISSUE THREAD

**Issue by emanov** [elkozmon/zoonavigator#39]
D:\Program\ZookeeperNavigator>docker-compose start
Starting api ... done
Starting web ... failed

D:\Program\ZookeeperNavigator>docker-compose logs
Attaching to zoonavigator-api
zoonavigator-api | [info] application - Starting ZooNavigator API 0.6.2
zoonavigator-api | [info] play.api.Play - Application started (Prod)
zoonavigator-api | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000
zoonavigator-api | [warn] a.a.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑'). Increase `akka.http.server.parsing.max-method-len
gth` to support HTTP methods with more characters.

**Comment by elkozmon** [comment]
Hi, 

what browser were you using? 
I've only seen a similar error when trying to access HTTP endpoint with HTTPS.

Anyway, there is a [new ZooNavigator release under a single Docker image](https://hub.docker.com/r/elkozmon/zoonavigator). 
You might want to try that and see whether the error still persists.
