### ISSUE TITLE
Setting HTTP_PORT=disabled makes docker healthcheck fail

### ISSUE THREAD

**Issue by sturcol** [elkozmon/zoonavigator#41]
While running the container with HTTPS only (and using the env vars described at https://www.elkozmon.com/zoonavigator/docker/configuration/) I encountered the docker container reporting a bad healthcheck.

Compose file:
version: '2'
services:
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    restart: always
    network_mode: bridge
    hostname: zoonavigator
    ports:
      - 9001:9001
    environment:
      - HTTP_PORT=disabled
      - HTTPS_PORT=9001

Portainer shows the following error: curl: (3) Port number ended with 'd'

It appears the issue lies in the healthcheck.sh file (https://github.com/elkozmon/zoonavigator/blob/master/build/docker/files/zoonavigator-api/healthcheck.sh.template)
since it assumes that the HTTP_PORT will always be defined.

**Comment by elkozmon** [comment]
Hi, thanks for reporting this! If you like, you can submit a PR, otherwise, I'll fix it sometime this week.

**Comment by elkozmon** [comment]
It should work well now in the new 0.7.1 release. Cheers!

**Comment by sturcol** [comment]
Works great, thanks for the quick fix.
