### ISSUE TITLE
[Feature Request] Multi-cluster support ?

### ISSUE THREAD

**Issue by Lowess** [elkozmon/zoonavigator#45]
Hi @elkozmon,

I just came across your project while looking for a potential replacement of our existing Zookeeper UI solution. First of all good job on all of that. I really appreciated reading the clean documentation / instructions you put together to run Zoo-navigator good job 👏 .

I wanted to know if you have any plan on supporting multiple zookeeper clusters from a single instance of ZooNavigator. There could be some sort of drop down allowing us to choose which cluster to connect to making it easy to switch from one to an other.

We run dozens of zookeeper clusters and that would make your project even more valuable to us.

Keep up the good work !
Thanks

**Comment by elkozmon** [comment]
Hi,

thank you very much, I'm glad you like it!

I like your idea. It'd be a nice addition to be able to switch between predefined ZK clusters like that. So, take that as a yes. I will work it in when I have the time.

Thanks :)

**Comment by elkozmon** [comment]
Hi, just a small update. I've already implemented what you requested, but there are some significant changes to the app configuration, so I need to update documentation first before I release a new version. It shouldn't take long though.

**Comment by Lowess** [comment]
Really nice to hear! I am excited about this upcoming release! Thanks for
the update

Le ven. 3 avr. 2020 à 13:45, Luboš Kozmon <notifications@github.com> a
écrit :

**Comment by elkozmon** [comment]
Hi,

so I finally released a build with this feature. You can find it in `latest` Docker image. Please, check out the documentation on how to setup up [multiple clusters](https://zoonavigator.elkozmon.com/en/latest/docker/preset-connections.html) and [auto connect](https://zoonavigator.elkozmon.com/en/latest/docker/autoconnect.html).

In case you come across any bugs/problems, I'd be happy to hear about it :) 

Thank you!

**Comment by Lowess** [comment]
Hi @elkozmon this is Amazing ! I will try to give it a spin asap and let you know about my feedback.

I am really thankful for this new feature ! I think it's a great addition ! 💪

**Comment by Lowess** [comment]
@elkozmon I gave the new version a try ! It works nicely from what I can tell as of today ! 

Thanks a lot for this addition. If you don't mind that would be great to release `elkozmon/zoonavigator:v1.0.0` so that projects can used a locked version of it.

**Comment by elkozmon** [comment]
Great, thank you for the feedback :)

I'm planning to release v1 sometime next week.
