### ISSUE TITLE
Make connection string / cluster name more visible on the UI

### ISSUE THREAD

**Issue by Lowess** [elkozmon/zoonavigator#46]
Right now in order to know what ZK cluster ZooNavigator is connected to, we have to go to `... > Session details`. That will be great to have it part of the top header banner.

The reason why I am suggesting this improvement is because we have a lot of ZK clusters running and it can be confusing for users when they land on the UI.

Let me know what you think about it @elkozmon 

Thanks !

**Comment by elkozmon** [comment]
Sure, this could come along with #45. 

I think having the dropdown show the active cluster and maybe also append it in the browsers tabs title should work, right?
