### ISSUE TITLE
Host not allowed: zoonavigator:9000

### ISSUE THREAD

**Issue by douglasramiro** [elkozmon/zoonavigator#47]
Hi,

I am starting the container as documentations asks:

docker run \
>   -d --network host \
>   -e HTTP_PORT=9000 \
>   --name zoonavigator \
>   --restart unless-stopped \
>   elkozmon/zoonavigator:latest

I can access the zoonavigator using the address localhost:9000

However, I am not able to access zoonavigator externally by hostname. I am receiving the following error:

{"success":false,"message":"Host not allowed: zoonavigator:9000"}

How to easily reproduce:

edit /etc/hosts and add zoonavigator to the line that begins with 127.0.0.1

Start the container with 

docker run \
>   -d --network host \
>   -e HTTP_PORT=9000 \
>   --name zoonavigator \
>   --restart unless-stopped \
>   elkozmon/zoonavigator:latest

Try to access the web application using a web browser.

I could not find any setting to allow a different host.

Thanks

**Comment by douglasramiro** [comment]
I could make it working by creating a new docker image changing the application.conf file.

`play {
  application.loader = AppLoader

  # HTTP configuration
  server.http.port = 9000

  # Session TTL in milliseconds
  http.session.maxAge = 900000

  # Allow large requests (imports)
  http.parser.maxMemoryBuffer = 10m

  # Allow all origins
  filters.cors.allowedOrigins = null

  # Filters
  filters {
    enabled = []
    enabled += "play.filters.headers.SecurityHeadersFilter"
    enabled += "play.filters.hosts.AllowedHostsFilter"
    enabled += "play.filters.cors.CORSFilter"
    #enabled += "play.filters.csrf.CSRFFilter"
  }

  **filters.hosts = {
    allowed = ["."]
  }**

  # Assets
  assets {
    path = "/public"
    urlPrefix = "/"
  }
}

zookeeper {
  # ZooKeeper client cache TTL in milliseconds
  client.maxAge = 5000

  # ZooKeeper client connection timeout in milliseconds
  client.connectTimeout = 5000
}
`

I am not sure if it is the best option....

**Comment by douglasramiro** [comment]
I could make it working by creating a new docker image changing the application.conf file

`play {
  application.loader = AppLoader

  # HTTP configuration
  server.http.port = 9000

  # Session TTL in milliseconds
  http.session.maxAge = 900000

  # Allow large requests (imports)
  http.parser.maxMemoryBuffer = 10m

  # Allow all origins
  filters.cors.allowedOrigins = null

  # Filters
  filters {
    enabled = []
    enabled += "play.filters.headers.SecurityHeadersFilter"
    enabled += "play.filters.hosts.AllowedHostsFilter"
    enabled += "play.filters.cors.CORSFilter"
    #enabled += "play.filters.csrf.CSRFFilter"
  }

  filters.hosts = {
    allowed = ["."]
  }

  # Assets
  assets {
    path = "/public"
    urlPrefix = "/"
  }
}
`

I just added the following snippet:

`filters.hosts = {
    allowed = ["."]
  }`

I am not sure if this is the best option.

**Comment by douglasramiro** [comment]
I could make it working by creating a new docker image changing the application.conf file

>play {
>  application.loader = AppLoader
>
>  # HTTP configuration
>  server.http.port = 9000
>
>  # Session TTL in milliseconds
>  http.session.maxAge = 900000
>
  # Allow large requests (imports)
  http.parser.maxMemoryBuffer = 10m

  # Allow all origins
  filters.cors.allowedOrigins = null

  # Filters
  filters {
    enabled = []
    enabled += "play.filters.headers.SecurityHeadersFilter"
    enabled += "play.filters.hosts.AllowedHostsFilter"
    enabled += "play.filters.cors.CORSFilter"
    #enabled += "play.filters.csrf.CSRFFilter"
  }

  filters.hosts = {
    allowed = ["."]
  }

  # Assets
  assets {
    path = "/public"
    urlPrefix = "/"
  }
}


I just added the following snippet:

filters.hosts = {
    allowed = ["."]
  }

I am not sure if this is the best option.

**Comment by douglasramiro** [comment]
I could make it work by changing the application.conf:


```bash
play {
  application.loader = AppLoader

  # HTTP configuration
  server.http.port = 9000

  # Session TTL in milliseconds
  http.session.maxAge = 900000

  # Allow large requests (imports)
  http.parser.maxMemoryBuffer = 10m

  # Allow all origins
  filters.cors.allowedOrigins = null

  # Filters
  filters {
    enabled = []
    enabled += "play.filters.headers.SecurityHeadersFilter"
    enabled += "play.filters.hosts.AllowedHostsFilter"
    enabled += "play.filters.cors.CORSFilter"
    #enabled += "play.filters.csrf.CSRFFilter"
  }

  filters.hosts = {
    allowed = ["."]
  }

  # Assets
  assets {
    path = "/public"
    urlPrefix = "/"
  }
}
```

I just included the following snippet:

```bash
filters.hosts = {
    allowed = ["."]
  }
```

I am not sure if it is the best option

**Comment by elkozmon** [comment]
Hi!

Ooops, I must have accidentally left the `play.filters.hosts.AllowedHostsFilter` filter enabled.

This only affects the `latest` docker image, so I'm gonna rebuild it in a minute.

Thank you for letting me know, and good job for coming up with your own fix btw :)

**Comment by elkozmon** [comment]
You can pull the new image now :)
