### ISSUE TITLE
Provide ZooKeeper host and auth via Docker

### ISSUE THREAD

**Issue by jhalterman** [elkozmon/zoonavigator#5]
Since I log into various ZooKeeper servers numerous times a day in dev and test environments, it would be nice if I could provide connection and auth information via Docker environment variables, and if zoonavogator-web could use that to establish a connection rather than prompting me to manually enter this info.

**Comment by elkozmon** [comment]
Sounds reasonable, I will include it in the next release along with ZNode [sorting](https://github.com/elkozmon/zoonavigator-web/issues/5) and [data wrapping](https://github.com/elkozmon/zoonavigator-web/issues/4). 
Thanks for the input :)
