### ISSUE TITLE
Multiple connection to server

### ISSUE THREAD

**Issue by Barbo96** [elkozmon/zoonavigator#52]
How can I specify two server in login phase, in order to change server if one crash without a new login?

I see that there is a dropdown called "Switch zookeeper connection", how can I use it?

In my deply don't work the import after an export, I try also to unzip but does't work.

**Comment by elkozmon** [comment]
Currently, you can only define multiple ZooKeeper clusters on application startup, not at the login.
See https://zoonavigator.elkozmon.com/en/latest/docker/preset-connections.html

Also, can you describe why import does not work? Some error message or something? Thank you.

**Comment by Barbo96** [comment]
For the import/export, I'm set in a node and click the button "Export", ZooNavigator download me a file.gz.
When I try to import the node exported before ZooNavigator give me the error: "Unsupported content type: application/x-gzip";
If I try to import the unzipped file.gz, zookeeper give me the error: "Unsupported content type: application/octet-stream"

**Comment by elkozmon** [comment]
Thank you, the error message is helpful. I'll create a new issue for this import/export bug and close this one which was primarily about multiple ZK cluster support.
