### ISSUE TITLE
Connect to zoonavigator api

### ISSUE THREAD

**Issue by michaelyefet** [elkozmon/zoonavigator#54]
hey,

I'm using zoonavigator and it's very convenient!

Lately we decided we need to create a script that manage some of the work with zookeeper.
I would like to use the zoonavigator api for this task (export/import/duplicate etc)

I didn't find documentation on the api. I managed to understood most of it.
The main problems right now are:
1) login (in version 0.8.0 I did it but i couldn't find how to do it in version 1.0.1)
2) import - couldn't find the data structure the api except to get.

If you can direct me on this issue or to some documentation it would be great!

**Comment by elkozmon** [comment]
Hi! 

There is no API documentation at the moment so I'll try to explain.

> login (in version 0.8.0 I did it but i couldn't find how to do it in version 1.0.1)

To log in you need to set the `Authorization` header like this: 
`Authorization: CxnParams <base64 encoded json>` 
and the JSON to be encoded should look like this:
```
{
 "connectionString": "localhost:2181",
 "authInfo": [{"scheme": "sasl", "id": "user@DOMAIN.COM"}]    <-- this is optional
}
```

> import - couldn't find the data structure the api except to get.

Import data structure looks like this:
```
[
   {
      "h":{
         "acl":[
            {
               "id":"anyone",
               "scheme":"world",
               "permissions":[
                  "read",
                  "admin",
                  "delete",
                  "write",
                  "create"
               ]
            }
         ],
         "path":"/test",
         "data":"aGVsbG8="
      },
      "t":[
         {
            "h":{
               "acl":[
                  {
                     "id":"anyone",
                     "scheme":"world",
                     "permissions":[
                        "read",
                        "admin",
                        "delete",
                        "write",
                        "create"
                     ]
                  }
               ],
               "path":"/test/child",
               "data":"d29ybGQ="
            },
            "t":[

            ]
         }
      ]
   }
]
```

It is a recursive scheme where `"h"` field refers to the parent node and `"t"` field refers to the children nodes of that parent node. Also, the value of `"data"` field is encoded using base64.

Since `0.8.0` you can import either directly as JSON, or as a gzipped file, but always set the `Content-Type` header accordingly to `application/json` or `application/gzip`.

Also, note that the API should not be considered public/stable and therefore can change in any release.

Please, let me know how it goes :)

**Comment by michaelyefet** [comment]
Thanks for the helpful reply.

I have another question.
When I try to export some znode path I receive hash I suppose its the relevant data.
later in my script i would like to import it back to tree so i need to transform him to the data structure you showed me. 
I tried to decode the data with base64 and it didn't work. can you give me some directions?

**Comment by elkozmon** [comment]
Right. The export data is first gzipped and then base64 encoded, so you're half-way there, you just have to ungzip the decoded data.

**Comment by michaelyefet** [comment]
Thanks that works great!

**Comment by elkozmon** [comment]
Glad to help :)

**Comment by michaelyefet** [comment]
Hi,
I have encountered another thing I'm not sure about.
I'm trying to create znode from the api.
1)What's the data structure that the creation post expects to get?
2) While assigning a value to the new znode waht's the data structure of the put method and do i have to add the znode version in the uri?

Thanks!

**Comment by elkozmon** [comment]
@michaelyefet 

> 1)What's the data structure that the creation post expects to get?
base64 encoded data in post request body

> 2) While assigning a value to the new znode waht's the data structure of the put method and do i have to add the znode version in the uri?
put method only updates already existing znode with new data, the request body is the same as above and yeah you have to provide the current znode version as a query parameter

**Comment by michaelyefet** [comment]
Im not sure i got it.
I am able to create new znode with post to a new path and it being created.
I am not able to create it with value or put value after it has been created.

1) I understand I need to send the data in base64 but in what json structure?
The data needs to be the same as I receive when I execute export request?

2)  Moreover, what about creating znode with permissions as it parent has?

thanks in advance

**Comment by elkozmon** [comment]
> 1. I understand I need to send the data in base64 but in what json structure? The data needs to be the same as I receive when I execute export request?

Content of the body is a JSON string of base64 encoded plain data. Lets say I want to update node data to a text `hello`.

(plain-data) `hello` -> (base64 enc)  `aGVsbG8=` -> (json string) `"aGVsbG8="`

> 2. Moreover, what about creating znode with permissions as it parent has?

ZooNavigator API does not implement that. You will have to set the permissions afterwards yourself.
