### ISSUE TITLE
How to build ZooNavigator docker image locally?

### ISSUE THREAD

**Issue by wf1nder** [elkozmon/zoonavigator#58]
I'm trying to build ZooNavigator docker image by myself. Using linux computer, i'm cloning repository, getting submodules content by following command:

`git submodule update --init --recursive`

which makes `zoonavigator-api` and `zoonavigator-web` directories not empty, and then try to build:

`docker build -t zoonavigator:mycustomversion build/docker`

But after some build steps getting error:

`Step 23/65 : COPY /zoonavigator-web .
COPY failed: stat /var/lib/docker/tmp/docker-builder077504063/zoonavigator-web: no such file or directory`

What am I doing wrong?

There is also a mention that it can be built without sbt/npm locally installed: https://github.com/elkozmon/zoonavigator/issues/4#issuecomment-338513431
Is this still true?

**Comment by elkozmon** [comment]
Hi,

take a look at this: https://zoonavigator.elkozmon.com/en/latest/docker/custom-url.html

There are instructions on how to build the Docker image. Ignore the part about `BASE_HREF`, that argument is not required.

**Comment by wf1nder** [comment]
Thank you, it worked!

Not the most obvious location in documentation :) I suggest mentioning this in the [Development guide](https://zoonavigator.elkozmon.com/en/latest/development.html) section of the wiki.

**Comment by elkozmon** [comment]
Good idea :)
