### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by kshitij91** [elkozmon/zoonavigator#59]
I followed the ref guide and the commands. 
Docker container is running fine, but when i go to localhost:9000 it says "this site can't be reached"

see attached screenshot for docker.

<img width="665" alt="Screenshot 2020-07-17 at 7 13 28 PM" src="https://user-images.githubusercontent.com/40487554/87793512-00dca880-c863-11ea-8046-849288a63263.png">

**Comment by elkozmon** [comment]
Hi,

what OS are you using as a Docker host?
also, could you please add the output of `docker inspect <zoonavigator-container-id>` command?
