### ISSUE TITLE
problem with "Adding auth entry to a Preset Connection"

### ISSUE THREAD

**Issue by AlexDormash** [elkozmon/zoonavigator#60]
Hello,
i have a problem with setting params  in 
`CONNECTION_<ID>_AUTH_<AUTHID>_SCHEME` 
and 
`CONNECTION_<ID>_AUTH_<AUTHID>_SCHEME`, 
i was successfully using `CONNECTION_LOCALZK_NAME` and `CONNECTION_LOCALZK_CONN`, it works for me, but when i try to add auth entry, ACL permissions doesn't work. I can't find documentation or examples what i need to set in variables `<ID>`, `<AUTHID>`.
f you can direct me on this issue or to some documentation or give me example it would be great!

**Comment by elkozmon** [comment]
Hi,

sorry, maybe it's a bit confusing in the documentation but `<ID>` is the connection id for which you're defining auth entries so in your case `LOCALZK`. `<AUTHID>` is chosen arbitrarily, like connection id, but obviously needs to match for the `CONNECTION_<ID>_AUTH_<AUTHID>_ID` and `CONNECTION_<ID>_AUTH_<AUTHID>_SCHEME` to produce a ACL entry pair.

So for example:

`CONNECTION_LOCALZK_NAME` = `my-local-zk`
`CONNECTION_LOCALZK_CONN` = `localhost:2181`
`CONNECTION_LOCALZK_AUTH_AUTH001_ID` = `user@DOMAIN.COM`
`CONNECTION_LOCALZK_AUTH_AUTH001_SCHEME` = `sasl`
`CONNECTION_LOCALZK_AUTH_AUTH002_ID` = `...`
`CONNECTION_LOCALZK_AUTH_AUTH002_SCHEME` = `...`

**Comment by AlexDormash** [comment]
ok, can i use it with scheme "digest"? 
If so, how it use in UI ACL in app?
I mean how to link it correctly ID from field ID in app tab ACL and `<AUTHID>` or there are another way?

See, in a image below there are scheme digest with user "test" and password "test", Id in a scheme digest forms as login:encoded(login:password) and we se it in a app as `test:V28q/NynI4JI3Rk54h0r8O5kMug=`
I tried different options to use id from ACL app in `CONNECTION_<ID>_AUTH_<AUTHID>_SCHEME`, `CONNECTION_<ID>_AUTH_<AUTHID>_SCHEME`, but all of them doesn't work. 
Can you help with it or this functionality not supported in app now?
![image](https://user-images.githubusercontent.com/28618368/88775995-11a7eb00-d18e-11ea-92b6-3fdfc34385cd.png)

**Comment by elkozmon** [comment]
You filled the UI ACL form correctly. I assume the problem is that you set the environment variables wrong.

According to [ZooKeeper docs](https://zookeeper.apache.org/doc/r3.5.2-alpha/zookeeperProgrammers.html) you need to authenticate using clear text user:pass, so try using these env variables:

```
CONNECTION_LOCALZK_AUTH_AUTH1_SCHEME=digest
CONNECTION_LOCALZK_AUTH_AUTH1_ID=test:test
```

I've just tested it and it works as expected (at least on latest build `36e5f4ce08c6`).

**Comment by AlexDormash** [comment]
Great, It works!
Thank you very much!)

**Comment by elkozmon** [comment]
Glad to help :)
