### ISSUE TITLE
feature request: read only session

### ISSUE THREAD

**Issue by amosbird** [elkozmon/zoonavigator#61]
Zoonavigator is an excellent product for managing zookeeper. However it seems a bit unsafe to host a shared service since anyone could modify any zknode... Is there any way to limit the access or perhaps provide a global read only view?

**Comment by elkozmon** [comment]
Thank you. There is no way to limit access or provide a read-only session at the moment. For now I can only suggest placing [basic auth proxy](https://zoonavigator.elkozmon.com/en/latest/faqs.html#how-to-enable-basic-authentication) in front of ZooNavigator. I agree that it is an important feature but it's not on my plan yet as it would require a bit more time than I can affrod to spend at the moment.

**Comment by amosbird** [comment]
Ok. I'll try limiting the access :). BTW, it does have a decent UI for preventing accidental modifications.
