### ISSUE TITLE
import using zoonavigator api

### ISSUE THREAD

**Issue by michaelyefet** [elkozmon/zoonavigator#64]
Hi,
I use the zoonavigator api in some inner scripts of our system.
I would like to be able to import znode with override(only insert the relevant changes). 
Is there a way to do this in the current api?

**Comment by elkozmon** [comment]
Hi, you can use update endpoint to do this in case the znode already exists. If it doesn't exist you could use the import endpoint, or create an empty znode and then do the update. No other way I'm afraid.
