### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by fizch** [elkozmon/zoonavigator#65]
I have followed the directions for running the docker container on windows 10, but I am getting the message that this site cannot be reached.

docker run -d --network host -e HTTP_PORT=9000 --name zoonavigator --restart unless-stopped elkozmon/zoonavigator:latest

I get this in the logs:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/app/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/lib/org.slf4j.slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] application - Enabling Filter: play.filters.headers.SecurityHeadersFilter
[info] application - Enabling Filter: play.filters.cors.CORSFilter
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

Based on another issue with the same problem, you asked for the docker inspect output:

[
    {
        "Id": "b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d",
        "Created": "2020-11-06T16:29:58.1144462Z",
        "Path": "./run.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 22772,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-06T16:31:08.8020611Z",
            "FinishedAt": "2020-11-06T16:31:05.0899912Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2020-11-06T16:31:38.8023706Z",
                        "End": "2020-11-06T16:31:39.0577325Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0
   0 --:--:-- --:--:-- --:--:--     0\r100  1945  100  1945    0     0   9487      0 --:--:-- --:--:-- --:--:--  9487\n\u003c!--\n  ~ Copyright (C) 2019  Ľuboš Kozmon \u003chttps://www.elkozmon.com\u003e\n  ~\n  ~ This program is free software: you can redistribute it and/or modify\n  ~ it under the terms of the GNU Affero General Public License as\n  ~ published by the Free Software Foundation, either version 3 of the\n  ~ License, or (at your option) any later version.\n  ~\n  ~ This program is distributed in the hope that it will be useful,\n  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of\n  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n  ~ GNU Affero General Public License for more details.\n  ~\n  ~ You should have received a copy of the GNU Affero General Public License\n  ~ along with this program.  If not, see \u003chttp://www.gnu.org/licenses/\u003e.\n  --\u003e\u003c!doctype html\u003e\n\u003chtml\u003e \n \u003chead\u003e \n  \u003cmeta charset=\"utf-8\"\u003e \n  \u003ctitle\u003eZooNavigator\u003c/title\u003e \n  \u003cbase id=\"base\" href=\"/\"\u003e \n  \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e \n  \u003clink rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"\u003e \n  \u003cscript\u003e\n    window['base-href'] = document.getElementById(\"base\").getAttribute(\"href\");\n  \u003c/script\u003e \n  \u003clink rel=\"stylesheet\" href=\"styles.39e0deb1b7410de5d1a6.css\"\u003e\n \u003c/head\u003e \n \u003cbody\u003e \u003czoo-app\u003e \n   \u003cdiv class=\"zoo-bootstrap\"\u003e \n    \u003cdiv class=\"zoo-center\"\u003e \n     \u003cdiv class=\"sk-folding-cube\"\u003e \n      \u003cdiv class=\"sk-cube1 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube2 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube4 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube3 sk-cube\"\u003e\u003c/div\u003e \n     \u003c/div\u003e \n    \u003c/div\u003e \n   \u003c/div\u003e \n  \u003c/zoo-app\u003e \n  \u003cscript type=\"text/javascript\" src=\"runtime.26209474bfa8dc87a77c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"polyfills.9aa3d12e54c7037b345c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"main.74e82960126732a4ecf9.js\"\u003e\u003c/script\u003e \n \u003c/body\u003e\n\u003c/html\u003e"
                    },
                    {
                        "Start": "2020-11-06T16:32:09.0700019Z",
                        "End": "2020-11-06T16:32:09.1326998Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0
   0 --:--:-- --:--:-- --:--:--     0\r100  1945  100  1945    0     0   146k      0 --:--:-- --:--:-- --:--:--  146k\n\u003c!--\n  ~ Copyright (C) 2019  Ľuboš Kozmon \u003chttps://www.elkozmon.com\u003e\n  ~\n  ~ This program is free software: you can redistribute it and/or modify\n  ~ it under the terms of the GNU Affero General Public License as\n  ~ published by the Free Software Foundation, either version 3 of the\n  ~ License, or (at your option) any later version.\n  ~\n  ~ This program is distributed in the hope that it will be useful,\n  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of\n  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n  ~ GNU Affero General Public License for more details.\n  ~\n  ~ You should have received a copy of the GNU Affero General Public License\n  ~ along with this program.  If not, see \u003chttp://www.gnu.org/licenses/\u003e.\n  --\u003e\u003c!doctype html\u003e\n\u003chtml\u003e \n \u003chead\u003e \n  \u003cmeta charset=\"utf-8\"\u003e \n  \u003ctitle\u003eZooNavigator\u003c/title\u003e \n  \u003cbase id=\"base\" href=\"/\"\u003e \n  \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e \n  \u003clink rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"\u003e \n  \u003cscript\u003e\n    window['base-href'] = document.getElementById(\"base\").getAttribute(\"href\");\n  \u003c/script\u003e \n  \u003clink rel=\"stylesheet\" href=\"styles.39e0deb1b7410de5d1a6.css\"\u003e\n \u003c/head\u003e \n \u003cbody\u003e \u003czoo-app\u003e \n   \u003cdiv class=\"zoo-bootstrap\"\u003e \n    \u003cdiv class=\"zoo-center\"\u003e \n     \u003cdiv class=\"sk-folding-cube\"\u003e \n      \u003cdiv class=\"sk-cube1 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube2 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube4 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube3 sk-cube\"\u003e\u003c/div\u003e \n     \u003c/div\u003e \n    \u003c/div\u003e \n   \u003c/div\u003e \n  \u003c/zoo-app\u003e \n  \u003cscript type=\"text/javascript\" src=\"runtime.26209474bfa8dc87a77c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"polyfills.9aa3d12e54c7037b345c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"main.74e82960126732a4ecf9.js\"\u003e\u003c/script\u003e \n \u003c/body\u003e\n\u003c/html\u003e"
                    },
                    {
                        "Start": "2020-11-06T16:32:39.1466345Z",
                        "End": "2020-11-06T16:32:39.2077061Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0
   0 --:--:-- --:--:-- --:--:--     0\r100  1945  100  1945    0     0   172k      0 --:--:-- --:--:-- --:--:--  172k\n\u003c!--\n  ~ Copyright (C) 2019  Ľuboš Kozmon \u003chttps://www.elkozmon.com\u003e\n  ~\n  ~ This program is free software: you can redistribute it and/or modify\n  ~ it under the terms of the GNU Affero General Public License as\n  ~ published by the Free Software Foundation, either version 3 of the\n  ~ License, or (at your option) any later version.\n  ~\n  ~ This program is distributed in the hope that it will be useful,\n  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of\n  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n  ~ GNU Affero General Public License for more details.\n  ~\n  ~ You should have received a copy of the GNU Affero General Public License\n  ~ along with this program.  If not, see \u003chttp://www.gnu.org/licenses/\u003e.\n  --\u003e\u003c!doctype html\u003e\n\u003chtml\u003e \n \u003chead\u003e \n  \u003cmeta charset=\"utf-8\"\u003e \n  \u003ctitle\u003eZooNavigator\u003c/title\u003e \n  \u003cbase id=\"base\" href=\"/\"\u003e \n  \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e \n  \u003clink rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"\u003e \n  \u003cscript\u003e\n    window['base-href'] = document.getElementById(\"base\").getAttribute(\"href\");\n  \u003c/script\u003e \n  \u003clink rel=\"stylesheet\" href=\"styles.39e0deb1b7410de5d1a6.css\"\u003e\n \u003c/head\u003e \n \u003cbody\u003e \u003czoo-app\u003e \n   \u003cdiv class=\"zoo-bootstrap\"\u003e \n    \u003cdiv class=\"zoo-center\"\u003e \n     \u003cdiv class=\"sk-folding-cube\"\u003e \n      \u003cdiv class=\"sk-cube1 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube2 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube4 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube3 sk-cube\"\u003e\u003c/div\u003e \n     \u003c/div\u003e \n    \u003c/div\u003e \n   \u003c/div\u003e \n  \u003c/zoo-app\u003e \n  \u003cscript type=\"text/javascript\" src=\"runtime.26209474bfa8dc87a77c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"polyfills.9aa3d12e54c7037b345c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"main.74e82960126732a4ecf9.js\"\u003e\u003c/script\u003e \n \u003c/body\u003e\n\u003c/html\u003e"
                    },
                    {
                        "Start": "2020-11-06T16:33:09.2234562Z",
                        "End": "2020-11-06T16:33:09.2812887Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0
   0 --:--:-- --:--:-- --:--:--     0\r100  1945  100  1945    0     0   211k      0 --:--:-- --:--:-- --:--:--  237k\n\u003c!--\n  ~ Copyright (C) 2019  Ľuboš Kozmon \u003chttps://www.elkozmon.com\u003e\n  ~\n  ~ This program is free software: you can redistribute it and/or modify\n  ~ it under the terms of the GNU Affero General Public License as\n  ~ published by the Free Software Foundation, either version 3 of the\n  ~ License, or (at your option) any later version.\n  ~\n  ~ This program is distributed in the hope that it will be useful,\n  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of\n  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n  ~ GNU Affero General Public License for more details.\n  ~\n  ~ You should have received a copy of the GNU Affero General Public License\n  ~ along with this program.  If not, see \u003chttp://www.gnu.org/licenses/\u003e.\n  --\u003e\u003c!doctype html\u003e\n\u003chtml\u003e \n \u003chead\u003e \n  \u003cmeta charset=\"utf-8\"\u003e \n  \u003ctitle\u003eZooNavigator\u003c/title\u003e \n  \u003cbase id=\"base\" href=\"/\"\u003e \n  \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e \n  \u003clink rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"\u003e \n  \u003cscript\u003e\n    window['base-href'] = document.getElementById(\"base\").getAttribute(\"href\");\n  \u003c/script\u003e \n  \u003clink rel=\"stylesheet\" href=\"styles.39e0deb1b7410de5d1a6.css\"\u003e\n \u003c/head\u003e \n \u003cbody\u003e \u003czoo-app\u003e \n   \u003cdiv class=\"zoo-bootstrap\"\u003e \n    \u003cdiv class=\"zoo-center\"\u003e \n     \u003cdiv class=\"sk-folding-cube\"\u003e \n      \u003cdiv class=\"sk-cube1 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube2 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube4 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube3 sk-cube\"\u003e\u003c/div\u003e \n     \u003c/div\u003e \n    \u003c/div\u003e \n   \u003c/div\u003e \n  \u003c/zoo-app\u003e \n  \u003cscript type=\"text/javascript\" src=\"runtime.26209474bfa8dc87a77c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"polyfills.9aa3d12e54c7037b345c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"main.74e82960126732a4ecf9.js\"\u003e\u003c/script\u003e \n \u003c/body\u003e\n\u003c/html\u003e"
                    },
                    {
                        "Start": "2020-11-06T16:33:39.2999709Z",
                        "End": "2020-11-06T16:33:39.3616177Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0
   0 --:--:-- --:--:-- --:--:--     0\r100  1945  100  1945    0     0   172k      0 --:--:-- --:--:-- --:--:--  189k\n\u003c!--\n  ~ Copyright (C) 2019  Ľuboš Kozmon \u003chttps://www.elkozmon.com\u003e\n  ~\n  ~ This program is free software: you can redistribute it and/or modify\n  ~ it under the terms of the GNU Affero General Public License as\n  ~ published by the Free Software Foundation, either version 3 of the\n  ~ License, or (at your option) any later version.\n  ~\n  ~ This program is distributed in the hope that it will be useful,\n  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of\n  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n  ~ GNU Affero General Public License for more details.\n  ~\n  ~ You should have received a copy of the GNU Affero General Public License\n  ~ along with this program.  If not, see \u003chttp://www.gnu.org/licenses/\u003e.\n  --\u003e\u003c!doctype html\u003e\n\u003chtml\u003e \n \u003chead\u003e \n  \u003cmeta charset=\"utf-8\"\u003e \n  \u003ctitle\u003eZooNavigator\u003c/title\u003e \n  \u003cbase id=\"base\" href=\"/\"\u003e \n  \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e \n  \u003clink rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"\u003e \n  \u003clink rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"\u003e \n  \u003cscript\u003e\n    window['base-href'] = document.getElementById(\"base\").getAttribute(\"href\");\n  \u003c/script\u003e \n  \u003clink rel=\"stylesheet\" href=\"styles.39e0deb1b7410de5d1a6.css\"\u003e\n \u003c/head\u003e \n \u003cbody\u003e \u003czoo-app\u003e \n   \u003cdiv class=\"zoo-bootstrap\"\u003e \n    \u003cdiv class=\"zoo-center\"\u003e \n     \u003cdiv class=\"sk-folding-cube\"\u003e \n      \u003cdiv class=\"sk-cube1 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube2 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube4 sk-cube\"\u003e\u003c/div\u003e \n      \u003cdiv class=\"sk-cube3 sk-cube\"\u003e\u003c/div\u003e \n     \u003c/div\u003e \n    \u003c/div\u003e \n   \u003c/div\u003e \n  \u003c/zoo-app\u003e \n  \u003cscript type=\"text/javascript\" src=\"runtime.26209474bfa8dc87a77c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"polyfills.9aa3d12e54c7037b345c.js\"\u003e\u003c/script\u003e\n  \u003cscript type=\"text/javascript\" src=\"main.74e82960126732a4ecf9.js\"\u003e\u003c/script\u003e \n \u003c/body\u003e\n\u003c/html\u003e"
                    }
                ]
            }
        },
        "Image": "sha256:bba0f630cf4fab7c41dd186f0c16cd9373b8a8d7db632faf670d9a938b1c272f",
        "ResolvConfPath": "/var/lib/docker/containers/b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d/hostname",
        "HostsPath": "/var/lib/docker/containers/b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d/hosts",
        "LogPath": "/var/lib/docker/containers/b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d/b0d9f1dc54cc7687700809d334d01e5bed2592b99d18303882c0e0d61e3aec9d-json.log",
        "Name": "/zoonavigator",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                64,
                238
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/c20231203c9ebf0f8d2c1e74502f0b5529999e09069c7f089e0da208dbabd8ef-init/diff:/var/lib/docker/overlay2/640bfcabf5c220811774ab71ba365a71beeaf1e594e2aa0ad2cbf6d8e28e8bb5/diff:/var/lib/docker/overlay2/e6873fb35dc677a1444de434723c84760a2dc762dc4c68d1d0c66fc34eb3d700/diff:/var/lib/docker/overlay2/b10f868e927808fe12542e5ff723bc87e3041c352163dec8712fa5ec9b35c5cf/diff:/var/lib/docker/overlay2/4142a2df5e2b75cc93cde1adbd3988d9e509f1c3e58a2934d0a426e9e30fcdbb/diff:/var/lib/docker/overlay2/b59fc3b14356a19649d323bec0bda8d723c40d469650f6f010418a1754951371/diff:/var/lib/docker/overlay2/0ff92b98dc2a6414b7a3fd40d00f997c1014220108941d3a8613a126bf53ee84/diff:/var/lib/docker/overlay2/eae2e5170eea7def1fb8fa33b91f204e7ef0fd3638151e82acda6540d182c789/diff:/var/lib/docker/overlay2/1484821b0244fc87e81ff92ff7f77b8191f26ce26f776d94facfae801cc9b89e/diff:/var/lib/docker/overlay2/c9de884c68fdeff4c36dbeb651c24dacd247be5dee9ecf00f0ea09e2024db93f/diff",
                "MergedDir": "/var/lib/docker/overlay2/c20231203c9ebf0f8d2c1e74502f0b5529999e09069c7f089e0da208dbabd8ef/merged",
                "UpperDir": "/var/lib/docker/overlay2/c20231203c9ebf0f8d2c1e74502f0b5529999e09069c7f089e0da208dbabd8ef/diff",
                "WorkDir": "/var/lib/docker/overlay2/c20231203c9ebf0f8d2c1e74502f0b5529999e09069c7f089e0da208dbabd8ef/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "docker-desktop",
            "Domainname": "",
            "User": "1000",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HTTP_PORT=9000",
                "PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/local/openjdk-11",
                "JAVA_VERSION=11.0.9",
                "REQUEST_MAX_SIZE_KB=10000",
                "REQUEST_TIMEOUT_MILLIS=10000",
                "ZK_CLIENT_TIMEOUT_MILLIS=5000",
                "ZK_CONNECT_TIMEOUT_MILLIS=5000"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "./healthcheck.sh"
                ],
                "Interval": 30000000000,
                "Timeout": 3000000000
            },
            "Image": "elkozmon/zoonavigator:latest",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "./run.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2020-11-03T09:47:14Z",
                "org.label-schema.description": "Web-based ZooKeeper UI/editor/browser",
                "org.label-schema.docker.cmd": "docker run -d --network host -e HTTP_PORT=9000 --name zoonavigator --restart unless-stopped elkozmon/zoonavigator:latest",
                "org.label-schema.name": "ZooNavigator",
                "org.label-schema.url": "https://zoonavigator.elkozmon.com/en/1.1.0",
                "org.label-schema.vcs-ref": "f3716a7",
                "org.label-schema.vcs-url": "https://github.com/elkozmon/zoonavigator",
                "org.label-schema.version": "1.1.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f199c8ce16a89035b2721fbb96f790cb2b2173e6034d7a075aa8e43a0f082417",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [],
                    "NetworkID": "1f39bc5cf1d4f3a83f7d5a62ef0012bb8cb0fd53afd9a9f121441249046ebc8a",
                    "EndpointID": "00c80db42ee736539a7e030311902f2f5b4df4c832cfd8cacafdf1240a533949",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by fizch** [comment]
I finally got it to work using the following docker run command. I removed the host network and exposed the port. For some reason, it wouldn't let me expose the port when using the host network.

docker run -e HTTP_PORT=9000 -p 9000:9000 --name zoonavigator --restart unless-stopped elkozmon/zoonavigator:latest

**Comment by henrik242** [comment]
Samehere on macOS.  I had to use `docker run   -d -p 9000:9000 -e HTTP_PORT=9000 --restart unless-stopped   elkozmon/zoonavigator:latest` to get it working. Docs should be updated.

**Comment by elkozmon** [comment]
You're correct, sorry guys. I'll update the docs right away.
