### ISSUE TITLE
Export zookeeper config with plain text format in a file

### ISSUE THREAD

**Issue by hamidgholami** [elkozmon/zoonavigator#69]
How can I have a all zookeeper configuration in a file with plain test format? Currently, It is encrypted when I get export from zoonavigator.

**Comment by elkozmon** [comment]
Hi! 

It is not encrypted, just compressed. If you un-gzip the contents, you will get raw data in JSON format. 

This is due to the fact that uncompressed exports can get quite big and people would need to manually tune server configuration to allow for large payloads to be able to import the data later.

**Comment by hamidgholami** [comment]
Hello,

Thank you for your response. But I mean "data: " field in JSON format as you can see in below.
`[
   {
      "h":{
         "acl":[
            {
               "id":"anyone",
               "scheme":"world",
               "permissions":[
                  "read",
                  "admin",
                  "delete",
                  "write",
                  "create"
               ]
            }
         ],
         "path":"/test",
         "data":"aGVsbG8="                         ***************** I want this data clearly *****************
      },
      "t":[
         {
            "h":{
               "acl":[
                  {
                     "id":"anyone",
                     "scheme":"world",
                     "permissions":[
                        "read",
                        "admin",
                        "delete",
                        "write",
                        "create"
                     ]
                  }
               ],
               "path":"/test/child",
               "data":"d29ybGQ="                         ***************** I want this data clearly *****************
            },
            "t":[

            ]
         }
      ]
   }
]`
Actually, I want to get a JSON  with all data. I want to search on zookeeper data.
Another question: Is there any way for export data in YAML format?

Best regards,
Hamid

**Comment by elkozmon** [comment]
Ah right, sorry. 

As for the data fields. It is base64 encoded, so you can easily decode it back to human-readable text. 

Again, the reasoning behind this is, that there have been requests for ZooNavigator to be able to edit binary data within Z-nodes (which it can now). Exporting such Z-nodes requires a binary-friendly format, hence the encoding.

And as for the YAML exports, sorry there is no way to do that. 
The best I can do is suggest something like this: https://www.json2yaml.com/

**Comment by elkozmon** [comment]
I'm aware that this is probably not the answer you were hoping for, but those are the limitations with exports.

I think, however, that such "search over Z-nodes data" is a feature worth implementing in itself.

**Comment by hamidgholami** [comment]
Thank you for your response
