### ISSUE TITLE
Kerberos principal as a user connecting to ZK

### ISSUE THREAD

**Issue by Tzaphkiel** [elkozmon/zoonavigator#71]
Hello, 

Nice application, usefull... but limited because I have a fully kerberized Hadoop cluster and some of those znodes are not accessible...

I usually specify the following:
* jaas-sasl-ssl.conf:  
  ```sh
  HbaseClient {
    com.sun.security.auth.module.Krb5LoginModule required
    useTicketCache=true;
  };
  ```

I then do: 
* `export JVMFLAGS="-Djava.security.auth.login.config=jaas-sasl-ssl.conf"`
* `kinit -k ${HBASE_PRINCIPAL} -t "${HBASE_KEYTAB_FILE}"` 
* call `zookeeper-client` utility   
  which then gives me access to the hbase znodes for example.

How would you achieve logging-in with a `principal` instead of a `username:password` ?

**Comment by elkozmon** [comment]
Hi!

There is [a configuration option](https://zoonavigator.elkozmon.com/en/latest/docker/configuration.html#java-jaas-login-config) in ZooNavigator that allows you to use your JAAS config (or [this one](https://zoonavigator.elkozmon.com/en/latest/snap/configuration.html#java-security-auth-login-config) you're running Snap distribution). You could put keytab file path in that config file. Also, make sure that you correctly set [context key](https://zoonavigator.elkozmon.com/en/latest/docker/configuration.html#zk-sasl-client-config) to be used for that config file. Given everything is configured correctly, I think it should work as you expect.

If you run into some issues, you can also enable [Kerberos debug mode](https://zoonavigator.elkozmon.com/en/latest/docker/configuration.html#java-krb5-debug) to get verbose debug logs which could help further.

**Comment by Tzaphkiel** [comment]
Thx, I'll give it a try soon.

Do you thing that by putting the above JAAS config (that asks to pick up the principal from the ticket cache), it would be able to load it ? I'm running ZooNavigator using Docker which would mean that anything to be loaded (like the keytab) would have to be passed to the container... or ?

By Context Key, do you actually mean 'Client' ?

**Comment by elkozmon** [comment]
Yes, you would have to pass the files to the container so they are on the same path as defined in the JAAS config file. If everything is set up correctly, I believe it should work.

Context key should be set depending on the JAAS config file you use. For example, for the config file you mentioned earlier, it would be `HbaseClient`.

**Comment by elkozmon** [comment]
You can have a look at some [examples in ZooKeeper docs](https://cwiki.apache.org/confluence/display/ZOOKEEPER/Client-Server+mutual+authentication) if you scroll down to Client configuration section. I used something very similar when I was testing SASL auth in ZooNavigator and it worked fine.
