### ISSUE TITLE
ACL Authentication for SASL

### ISSUE THREAD

**Issue by afzouni** [elkozmon/zoonavigator#73]
Hi,
Zoonavigator Can't working with ACL and **SASL**; I filled login form with `admin` credential of zookepeer (`Auth username`, `Auth password` fields) but when I click on a node which has ACL for `admin` retuned this error:
```
Error: KeeperErrorCode = NoAuth for /node1
```

Note that I can connect to zookepeer  with these credentials using Python Script.

![Screenshot from 2021-06-07 08-53-06](https://user-images.githubusercontent.com/7107254/120958993-55716680-c748-11eb-838e-043c796a182d.png)

**Comment by elkozmon** [comment]
Hi,

I'm not sure if I understand your problem. Auth username and password fields in ZooNavigator aren't used for SASL authentication, but for DIGEST authentication.

Let's say you have a ZooKeeper node and assign it exclusively this ACL entry with all permissions:
scheme: `digest`
id: `admin:x1nq8J5GOJVPY6zgzhtTtA9izLc=` (this expression stands for username: `admin` and base64 encoded sha1 digest password: `admin` as required by ZooKeeper)

If you connect to this ZooKeeper using ZooNavigator while entering `admin` as auth username and password, you will be able to open/write/delete this node.

**Comment by afzouni** [comment]
Hi Dear, 
Authentication using `digest` is working good as good and it's okay. For a specific case, I need authenticate in ZooNavigator using `SASL`.

**Comment by elkozmon** [comment]
To use SASL authentication, you have to provide JAAS configuration file to ZooNavigator.

I assume you wish to authenticate with ZooNavigator using DIGEST-MD5 SASL auth (i.e. username and password). If that's the case then the config file needs to look like this (with your username and password):
```
Client {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       username="admin"
       password="admin";
};
```

You need to set the path to the JAAS config file in ZooNavigator, which in case you are using Docker image, can be done using `JAVA_JAAS_LOGIN_CONFIG` environment variable.
