### ISSUE TITLE
need website safety

### ISSUE THREAD

**Issue by yongdi** [elkozmon/zoonavigator#8]
can you provide a basic authentication just like rockmongo? our zk is no-password so everybody can modify via this website. only a user/password needed, for log in the website

**Comment by elkozmon** [comment]
If you want basic auth on ZooNavigator it's only a matter of providing custom nginx config ([see default template](https://github.com/elkozmon/zoonavigator-web/blob/master/docker/copy/etc/nginx/nginx.conf.template)). I shall provide an example on how to do so in README but assuming you are running ZooNavigator web client in Docker, you should mount modified config to the container at path _/etc/nginx/nginx.conf.template_ (note that this is a Go template)

My reason for not including basic auth out of the box is that ideally, you should be using Zookeeper ACLs for this.

**Comment by yongdi** [comment]
ok, I see. using nginx auth is a good solution. thank you for answering in time, add a star for this

**Comment by elkozmon** [comment]
You are welcome :)
