### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by vkarakaya** [elkozmon/zoonavigator#83]
Hi, currently there is no arm64 support in docker images. I tried running amd64 builded version in arm64 vm but there is no easy way to do that. Could you please add arm64 support while building docker images?

**Comment by elkozmon** [comment]
Working on it :)

**Comment by thinkingmonster** [comment]
HI @elkozmon  is there any progress on arm64 images? I tried to build one but have not been successful so far.

**Comment by elkozmon** [comment]
Hi! Yes actually. I've got to a point where I'm able to build the image, but didn't have time to finish the rest of the CI pipeline. But since it's broken now anyway I'll release it as it is now so you can try out the image (I haven't yet).

**Comment by elkozmon** [comment]
Sorry this took so long. I pushed the new image to Docker Hub as `elkozmon/zoonavigator:unstable`. 

PS: I didn't have time to actually run the image, so fingers crossed. If you do try it out, please let me know how it went. Thanks.

**Comment by abbeshamza** [comment]
hello, i tried to run the new image. it is not working for me i get a white page.

**Comment by elkozmon** [comment]
> hello, i tried to run the new image. it is not working for me i get a white page.

Sorry to hear that, but thanks for letting me know. I will look into it.

**Comment by elkozmon** [comment]
Version `1.1.3` is now out with Docker image for arm64!
