### ISSUE TITLE
Can not build: the version of node.js should be bump to at least 14.20.0

### ISSUE THREAD

**Issue by Gleiphir2769** [elkozmon/zoonavigator#85]
Currently, the version of node.js base image is 14.18, which can't pass the version check of @angular/cli@16.0.3.

https://github.com/elkozmon/zoonavigator/blob/92f0cf75dddc5afabe409062cf4cb8b9190c11a2/build/docker/Dockerfile#L27

![image](https://github.com/elkozmon/zoonavigator/assets/50270213/f04d20f9-19d2-48db-9916-8d26731733f4)

I think we need to bump node version to 14.20.1 because it is the minimum version that compiles successfully under my test

**Comment by elkozmon** [comment]
You are right, thanks for letting me know. I will bump the version along with some other updates soon.
