### ISSUE TITLE
Binary file in Zoonavigator

### ISSUE THREAD

**Issue by artempostnikov1** [elkozmon/zoonavigator#87]
<img width="947" alt="image" src="https://github.com/elkozmon/zoonavigator/assets/31702367/649ea34d-1f67-46cf-969f-8768771e7b77">
When I open file in zoonavigator, I see this. Are there any opportunities to change encoding or something like that?

**Comment by elkozmon** [comment]
Hi! Sure, just click the mode button and pick base64 encoding ;)

**Comment by artempostnikov1** [comment]
It's not the case I guess
<img width="602" alt="image" src="https://github.com/elkozmon/zoonavigator/assets/31702367/50e140c5-dd43-4ee9-8f30-7c7688a4ffba">
<img width="1347" alt="image" src="https://github.com/elkozmon/zoonavigator/assets/31702367/940e7f0b-842e-4e26-b865-f70a3faff50f">

**Comment by elkozmon** [comment]
The editor should be showing the base64 encoded contents of the binary file, is that not the case? It also allows you to update the file with modified base64 string.

**Comment by artempostnikov1** [comment]
It's encoded in some way string, could I use my own codec in zoo navigator?

**Comment by elkozmon** [comment]
No, sorry, that's not possible. 

However you can still use the base64 mode like this:
- Copy the base64 string to a file on your computer
- Decode the file using base64 to get the file in binary format
- Make the changes you want to the binary file locally
- Encode the binary file back to base64 string
- Copy-paste the updated base64 string to zoonavigator (make sure base64 mode is still active) and save the changes

**Comment by elkozmon** [comment]
You're welcome!
