### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by ayyappaappana** [elkozmon/zoonavigator#9]
Hi,

I am new to this zookeeper as part of research i started zookeeper server using docker-compose and zoonavigator too. but while connecting thru my nodejs script, i havent provided any username and password in my local linux instance.

this is my zookeeper server 

zookeeper:
    container_name: zookeeper
    image: "zookeeper"    
    ports:
      - "2181:2181"

and for web, i used this zookeeper docker. What are the details to enter ? can you please guide me.

**Comment by elkozmon** [comment]
Hi,

if ZooNavigator is defined in the same docker-compose file, then you would enter `zookeeper:2181` as a connection string and click _Connect_. I created a [gist of such docker-compose](https://gist.github.com/elkozmon/85a3eaee0f0cc2c613c932f0d7745180) file for you. You don't have to enter any username/password.

**Comment by elkozmon** [comment]
I am closing this issue for now. In case you are still having trouble feel free to reopen it. :)
